import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

const noStore = {
  "Cache-Control": "no-store, no-cache, must-revalidate, private",
  Pragma: "no-cache",
  Expires: "0",
};

type Dataset = "users" | "groups" | "loans" | "investments" | "audit_logs";

const DATASET_FN: Record<Dataset, string> = {
  users: "get_secure_users_full",
  groups: "get_secure_groups_full",
  loans: "get_secure_loans_full",
  investments: "get_secure_investments_full",
  audit_logs: "get_secure_audit_logs_full",
};

function toCSV(rows: any[]): string {
  if (!rows || rows.length === 0) return "";
  const headers = Array.from(
    rows.reduce((set: Set<string>, r) => {
      Object.keys(r || {}).forEach((k) => set.add(k));
      return set;
    }, new Set<string>())
  );
  const esc = (v: any) => {
    if (v === null || v === undefined) return "";
    const s = typeof v === "object" ? JSON.stringify(v) : String(v);
    return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
  };
  const lines = [headers.join(",")];
  for (const r of rows) lines.push(headers.map((h) => esc((r as any)[h])).join(","));
  return lines.join("\n");
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, ...noStore, "Content-Type": "application/json" },
      });
    }

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: authHeader } } }
    );

    const token = authHeader.replace("Bearer ", "");
    const { data: claims, error: cErr } = await supabase.auth.getClaims(token);
    if (cErr || !claims?.claims?.sub) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, ...noStore, "Content-Type": "application/json" },
      });
    }

    const body = await req.json().catch(() => ({}));
    const dataset = body?.dataset as Dataset;
    const format = (body?.format as string) || "csv";
    const secureToken = body?.secure_token as string;
    const exportId = crypto.randomUUID();

    if (!dataset || !DATASET_FN[dataset]) {
      return new Response(JSON.stringify({ error: "Invalid dataset" }), {
        status: 400,
        headers: { ...corsHeaders, ...noStore, "Content-Type": "application/json" },
      });
    }
    if (!secureToken) {
      return new Response(JSON.stringify({ error: "Missing secure session token" }), {
        status: 401,
        headers: { ...corsHeaders, ...noStore, "Content-Type": "application/json" },
      });
    }
    if (!["csv", "json"].includes(format)) {
      return new Response(JSON.stringify({ error: "Unsupported format" }), {
        status: 400,
        headers: { ...corsHeaders, ...noStore, "Content-Type": "application/json" },
      });
    }

    // Server-side fetch via PIN-gated RPC
    const { data, error } = await supabase.rpc(DATASET_FN[dataset], {
      _token: secureToken,
    });
    if (error) {
      return new Response(JSON.stringify({ error: error.message }), {
        status: 403,
        headers: { ...corsHeaders, ...noStore, "Content-Type": "application/json" },
      });
    }

    const rows = Array.isArray(data) ? data : [];

    // Audit log
    await supabase.rpc("log_secure_export", {
      _token: secureToken,
      _dataset: dataset,
      _format: format,
      _row_count: rows.length,
    });

    const stamp = new Date().toISOString().replace(/[:.]/g, "-");
    const filename = `amana-${dataset}-${stamp}.${format}`;
    const watermark = `# Generated by Amana Secure Vault • Admin: ${claims.claims.sub} • Export: ${exportId} • ${new Date().toISOString()}\n`;

    if (format === "csv") {
      const body = watermark + toCSV(rows);
      return new Response(body, {
        status: 200,
        headers: {
          ...corsHeaders,
          ...noStore,
          "Content-Type": "text/csv; charset=utf-8",
          "Content-Disposition": `attachment; filename="${filename}"`,
          "X-Export-Id": exportId,
        },
      });
    }

    const json = JSON.stringify(
      { meta: { dataset, export_id: exportId, generated_at: new Date().toISOString(), rows: rows.length }, data: rows },
      null,
      2
    );
    return new Response(json, {
      status: 200,
      headers: {
        ...corsHeaders,
        ...noStore,
        "Content-Type": "application/json",
        "Content-Disposition": `attachment; filename="${filename}"`,
        "X-Export-Id": exportId,
      },
    });
  } catch (e) {
    return new Response(JSON.stringify({ error: (e as Error).message }), {
      status: 500,
      headers: { ...corsHeaders, ...noStore, "Content-Type": "application/json" },
    });
  }
});
